'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer'
import Header from '@/components/header'
import {BrowserRouter as Router} from "react-router-dom";


const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

//TODO schrijf een script om de query werkend te krijgen.

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <Router>
        <body>
        <Header/>
        <main className={inter.className}>{children}</main>
        <Footer/>
        </body>
      </Router>
      </html>

  )
}
